### PR TITLE
Evaluation of the level of decentralization in Ethereum

### PR DESCRIPTION
**Pull request by GuillaumeDonnet**

### CODE REVIEW

**Comment by christina-tkach** [comment]
@CitronPerfide thank you for participating in the challenge! could you please submit your solution as an .md file?

**Comment by GuillaumeDonnet** [comment]
[GuillaumeDonnet.md](https://github.com/1712n/decentralization-challenge/files/12327553/GuillaumeDonnet.md)

**Comment by GuillaumeDonnet** [comment]
> @CitronPerfide thank you for participating in the challenge! could you please submit your solution as an .md file?

Hello yes, I put the file in the comments here and i also opened a new PR with the .md file. Thank you

**Comment by christina-tkach** [comment]
Closing this one as I already merged the new PR you opened

**Pull request closed without merging**
